browsersync:
  notify: true
  open: false
  port: 3000
  server:
    basedir: "."
  xip: false

javascript:
  dest:
    root: "./assets/js"
  front:
    # filename to output
    filename: "script.js"
    notification: "Running JavaScript"
    # Paths to JavaScript libraries, which are combined into one file
    vendor:
      - "bower_components/foundation-sites/js/foundation.core.js"
      - "bower_components/foundation-sites/js/foundation.util.keyboard.js"
      - "bower_components/foundation-sites/js/foundation.util.box.js"
      - "bower_components/foundation-sites/js/foundation.util.nest.js"
      - "bower_components/foundation-sites/js/foundation.util.mediaQuery.js"
      - "bower_components/foundation-sites/js/foundation.util.triggers.js"
      - "bower_components/foundation-sites/js/foundation.util.motion.js"
      - "bower_components/foundation-sites/js/foundation.dropdownMenu.js"
      - "bower_components/foundation-sites/js/foundation.offcanvas.js"
      - "bower_components/foundation-sites/js/foundation.sticky.js"
      - "bower_components/foundation-sites/js/foundation.magellan.js"
    src:
      # Paths to your own project code are here
      # All the files in this list and in the js dir are concatenated into script.js
      - "build/js/**/*.js"
      - "!build/js/admin/**/*.js"
  admin:
    filename: "admin.js"
    notification: "Running Admin JavaScript"
    src:
      - "build/js/admin/**/*.js"
  server:
    filename: "server.js"
    notification: "Running Server JavaScript"
    src:
      - "build/js/server/server.js"

sass:
  # Autoprefixer will make sure your CSS works with these browsers
  compatibility:
    - "last 2 versions"
    - "ie >= 9"
  dest:
    root: "./assets/css"
  front:
    filename: "style.css"
    notification: "Running Sass"
    vendor:
      - "bower_components/foundation-sites/scss"
      - "bower_components/motion-ui/src"
    src: "build/sass/main.scss"
  admin:
    filename: "admin.css"
    notification: "Running Admin Sass"
    src: "build/sass/admin/main.scss"

watch:
  javascript:
    front:
      - "build/js/**/*.js"
      - "!build/js/admin/**/*.js"
      - "!build/js/tinymce/**/*.js"
    admin: "build/js/admin/**/*.js"
    server: "build/js/server/sever.js"
  sass: 
    front: 
      - "build/sass/**/*.scss"
      - "!build/sass/admin/**/*.scss"
    admin: "build/sass/admin/**/*.scss"
